import { icons, images, SIZES, COLORS, FONTS } from '../constants'
// export default [
//     {
//       "album_id": "cbc1e09c-55c5-47fd-ad99-264c06e32765",
//       "description": "hokagas",
//       "name": "Family Dynasty",
//       "favourite": true,
//       "time": "2021-12-10T09:20:58.546140Z",
//       "deleted": false,
//       "private": true,
//       "URL": images.burger_restaurant_1,
//       "number_of_members": 5
//     },
//     {
//       "album_id": "f1c3f8f3-fd18-4d4d-a524-4bf4c0267c56",
//       "description": "Best in the world",
//       "name": "Queens of Hearts.",
//       "favourite": true,
//       "time": "2021-12-10T09:18:14.725290Z",
//       "deleted": false,
//       "private": true,
//       "URL": images.pizza_restaurant,
//       "number_of_members": 10
//     },
//     {
//       "album_id": "f1c3f8f3-fd08-4d4d-a524-4bf4c0287c56",
//       "description": "Best in the world",
//       "name": "Shipunden",
//       "favourite": false,
//       "time": "2021-12-10T09:18:14.725290Z",
//       "deleted": false,
//       "private": true,
//       "URL": images.hot_dog_restaurant,
//       "number_of_members": 2
//     }
//   ]
export default [
    {
        id: 1,
        name: "Aluko Family of Greats",
        number_of_members: 48,
        favourite: true,
        photo: images.burger_restaurant_1,
        posts: [
            {
                postId: 1,
                userprofile: icons.user,
                username: "Blake Carinton",
                type:'image',
                photo: images.crispy_chicken_burger,
                comment: "Remember that time that we went to see mr buscuit , it was mad we almost eat him finish , he was cring ehh",
                fire: true,
                time:"8m",
            },
            {
                postId: 2,
                userprofile: icons.user,
                username: "Falon Carinton",
                type:'text',
                comment: "Who can Remember the time we all when to mozabiq that we met Jonny English , It was mad . Brother didnt even waste time to eat the food there",
                fire: true,
                time:"8m",
            },
            {
                postId: 3,
                userprofile: icons.user,
                username: "Anders",
                type:'image',
                photo:images.pizza_restaurant,
                comment: "It was mad we almost eat him finish , he was cring ehh",
                fire:   false,
                time:"8m",
            },
            {
                postId: 4,
                userprofile: icons.user,
                username: "Blake Carinton",
                type:'video',
                video: images.crispy_chicken_burger,
                comment: "Remember that time that we went to see mr buscuit , it was mad we almost eat him finish , he was cring ehh",
                fire: true,
            },
            {
                postId: 5,
                userprofile: icons.user,
                username: "Blake Carinton",
                type:'audio',
                audio: images.crispy_chicken_burger,
                comment: "Remember that time that we went to see mr buscuit , it was mad we almost eat him finish , he was cring ehh",
                fire: true,
            },
        ]
    },
    {
        id: 2,
        name: "Teens of Aluko",
        number_of_members: 28,
        favourite: false,
        photo: images.pizza_restaurant,
        posts: [
            {
                postId: 1,
                userprofile: icons.user,
                username: " Wendy Rhoades",
                type:'text',
                comment: "Who can Remember the time we all when to mozabiq that we met Jonny English , It was mad . Brother didnt even waste time to eat the food there",
                fire: true,
                time:"1h",
            },
            {
                postId: 2,
                userprofile: icons.user,
                username: "Bobby Axelrod",
                type:'image',
                photo: images.hawaiian_pizza,
                comment: "Remember that time that we went to see mr buscuit , it was mad we almost eat him finish , he was cring ehh",
                fire: false,
                time:"8m",
            },
            {
                postId: 3,
                userprofile: icons.user,
                username: "Chuck Rhoades",
                type:'image',
                photo:images.pizza_restaurant,
                comment: "It was mad we almost eat him finish , he was cring ehh",
                fire:   false,
                time:"8m",
            },
            {
                postId: 4,
                userprofile: icons.user,
                username: "Dollar Bill",
                type:'text',
                comment: "Who can Remember the time we all when to mozabiq that we met Jonny English , It was mad . Brother didnt even waste time to eat the food there",
                fire: true,
                time:"1h",
            },
            {
                postId: 5,
                userprofile: icons.user,
                username: "Blake Carinton",
                type:'video',
                video: images.crispy_chicken_burger,
                comment: "Remember that time that we went to see mr buscuit , it was mad we almost eat him finish , he was cring ehh",
                fire: true,
            },
            {
                postId: 6,
                userprofile: icons.user,
                username: "Blake Carinton",
                type:'audio',
                audio: images.crispy_chicken_burger,
                comment: "Remember that time that we went to see mr buscuit , it was mad we almost eat him finish , he was cring ehh",
                fire: true,
            },
        ]
    },
    {
        id: 3,
        name: "Stalwart of Academy",
        number_of_members: 128,
        favourite: true,
        photo: images.hot_dog_restaurant,
        posts: [
            {
                postId: 1,
                userprofile: icons.user,
                username: "Joe Goldberg",
                type:'image',
                photo: images.chicago_hot_dog,
                comment: "he was cring ehh",
                fire: true,
                time:"8m",
            },
            {
                postId: 2,
                userprofile: icons.user,
                username: "Love Quinn",
                type:'text',
                comment: "Who can Remember the time we all when to mozabiq that we met Jonny English , It was mad . Brother didnt even waste time to eat the food there",
                fire: true,
                time:"8m",
            },
            {
                postId: 3,
                userprofile: icons.user,
                username: "Anders",
                type:'video',
                photo:images.pizza_restaurant,
                comment: "It was mad we almost eat him finish , he was cring ehh",
                fire:   false,
                time:"8m",
            },
            {
                postId: 4,
                userprofile: icons.user,
                username: "Blake Carinton",
                type:'video',
                video: images.crispy_chicken_burger,
                comment: "Remember that time that we went to see mr buscuit , it was mad we almost eat him finish , he was cring ehh",
                fire: true,
            },
            {
                postId: 5,
                userprofile: icons.user,
                username: "Blake Carinton",
                type:'audio',
                audio: images.crispy_chicken_burger,
                comment: "Remember that time that we went to see mr buscuit , it was mad we almost eat him finish , he was cring ehh",
                fire: true,
            },
        ]
    },


];


