export const REGISTER_LOADING = 'REGISTER_LOADING';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGIN_LOADING = 'LOGIN_LOADING';
export const CLEAR_AUTH_STATE = 'CLEAR_AUTH_STATE';
export const LOGOUT_USER = 'LOGOUT_USER';

export const GET_ALBUMS_LOADING = 'GET_ALBUMS_LOADING';
export const GET_ALBUMS_SUCCESS = 'GET_ALBUMS_SUCCESS';
export const GET_ALBUMS_FAIL = 'GET_ALBUMS_FAIL';

export const CREATE_ALBUM_LOADING = 'CREATE_ALBUM_LOADING';
export const CREATE_ALBUM_SUCCESS = 'CREATE_ALBUM_SUCCESS';
export const CREATE_ALBUM_FAIL = 'CREATE_ALBUM_FAIL';

export const DELETE_ALBUM_LOADING = 'DELETE_ALBUM_LOADING';
export const DELETE_ALBUM_SUCCESS = 'DELETE_ALBUM_SUCCESS';
export const DELETE_ALBUM_FAIL = 'DELETE_ALBUM_FAIL';

export const EDIT_ALBUM_LOADING = 'EDIT_ALBUM_LOADING';
export const EDIT_ALBUM_SUCCESS = 'EDIT_ALBUM_SUCCESS';
export const EDIT_ALBUM_FAIL = 'EDIT_ALBUM_FAIL';

export default {
    REGISTER_LOADING ,
    REGISTER_SUCCESS ,
    REGISTER_FAIL ,
    LOGIN_SUCCESS ,
    LOGIN_FAIL ,
    LOGIN_LOADING ,
    CLEAR_AUTH_STATE ,
    LOGOUT_USER ,

    GET_ALBUMS_LOADING ,
    GET_ALBUMS_SUCCESS ,
    GET_ALBUMS_FAIL,

    CREATE_ALBUM_LOADING ,
    CREATE_ALBUM_SUCCESS ,
    CREATE_ALBUM_FAIL,

    DELETE_ALBUM_LOADING ,
    DELETE_ALBUM_SUCCESS ,
    DELETE_ALBUM_FAIL ,

    EDIT_ALBUM_LOADING ,
    EDIT_ALBUM_SUCCESS ,
    EDIT_ALBUM_FAIL

}